import type { Metadata } from "next";
import FullWidthContainer from "@/components/FullWidthContainer";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <FullWidthContainer>
      <Navbar />
      {children}
    </FullWidthContainer>
  );
}
